# Generated by Django 3.2.22 on 2023-10-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_expense_flight_return_ticket_expense_place_of_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='departure',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
